# Generated by Django 5.2.8 on 2025-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Centro')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Centro activo')),
            ],
        ),
    ]
