# Generated by Django 5.2.8 on 2025-11-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centro',
            options={'ordering': ['nombre'], 'verbose_name': 'Centro', 'verbose_name_plural': 'Centros'},
        ),
    ]
