# Generated by Django 5.2.8 on 2025-11-19 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=250, verbose_name='Correo Electrónico')),
                ('phone', models.IntegerField(max_length=9, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
