# Generated by Django 5.2.8 on 2025-11-26 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=300, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('birthdate', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('OTRO', 'Otro')], default=None, max_length=10, null=True, verbose_name='Género')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TRABAJADOR', 'Trabajador'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10, verbose_name='Rol')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('reward_points', models.IntegerField(default=0, verbose_name='Balanzen Points')),
                ('membership_level', models.CharField(choices=[('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino')], default='PLATA', max_length=10)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_session', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
