# Generated by Django 5.2.8 on 2025-11-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionusuario',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Sesión de Usuario', 'verbose_name_plural': 'Sesiones de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
