# Generated by Django 5.2.8 on 2026-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sesionusuario_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['email'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(null=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-14 12:00:00', verbose_name='fecha_creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha_actualizacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SesionUsuario',
        ),
    ]
