# Generated by Django 5.2.8 on 2025-11-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_usersession_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Clase')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='classes.classes')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='users.user')),
            ],
        ),
    ]
