# Generated by Django 5.2.8 on 2025-11-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Clase')),
                ('description', models.CharField(verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('id_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Centro', to='centers.center')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('max_capacity', models.IntegerField(verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.classtype')),
            ],
        ),
    ]
