# Generated by Django 5.2.8 on 2025-11-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_clase', to='centers.centro', verbose_name='Centro')),
            ],
            options={
                'verbose_name': 'Tipo de Clase',
                'verbose_name_plural': 'Tipos de Clase',
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('activa', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('tipo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='classes.tipoclase', verbose_name='Tipo de Clase')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
            },
        ),
    ]
