# Generated by Django 5.2.8 on 2025-11-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionclase',
            options={'ordering': ['-fecha', 'hora_inicio'], 'verbose_name': 'Sesión de Clase', 'verbose_name_plural': 'Sesiones de Clase'},
        ),
        migrations.AlterModelOptions(
            name='tipoclase',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Clase', 'verbose_name_plural': 'Tipos de Clase'},
        ),
    ]
